### ISSUE TITLE
ValueError: ',' is not a valid scope name

### ISSUE THREAD

**Issue by timpal0l** [bjherger/keras-pandas#98]
`data_type_dict = {'numerical': ['lexical__avg_sen_len', 'lexical__std_sen_len', 'lexical__lex_diversity', 'characters__,' ,'characters__,d', 'characters__,m', 'label']}`
`output_var = 'label'`
`auto = Automater(data_type_dict=data_type_dict, output_var=output_var)`

I have a few numerical features, where the one named `characters__,` seems to cause problem due to the comma symbol. Any way to get around this without renaming the features?

> ~/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in name_scope(self, name)
   4002         # op name regex, which constrains the initial character.
   4003         if not _VALID_OP_NAME_REGEX.match(name):
-> 4004           raise ValueError("'%s' is not a valid scope name" % name)
   4005     old_stack = self._name_stack
   4006     if not name:  # Both for name=None and name="" we re-set to empty scope.
    ValueError: 'input_characters__,' is not a valid scope name

**Comment by bjherger** [comment]
Or could you try a `pip install -U keras-pandas`, and re-running your code?

**Comment by bjherger** [comment]
Addressed in 3.0.1
